networks:
  mfp-network:
    driver: bridge

services:
  container:
    image: mfp/react:latest
    container_name: mfp-container
    build:
      context: ../packages/container
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - mfp-network
    volumes:
      - ../packages/container:/usr/src/app
      - /usr/src/app/node_modules
  marketing:
    image: mfp/react:latest
    container_name: mfp-marketing
    build:
      context: ../packages/marketing
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - mfp-network
    volumes:
      - ../packages/marketing:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    image: mfp/react:latest
    container_name: mfp-auth
    build:
      context: ../packages/auth
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    networks:
      - mfp-network
    volumes:
      - ../packages/auth:/usr/src/app
      - /usr/src/app/node_modules
  dashboard:
    image: mfp/vue:latest
    container_name: mfp-dashboard
    build:
      context: ../packages/dashboard
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    networks:
      - mfp-network
    volumes:
      - ../packages/dashboard:/usr/src/app
      - /usr/src/app/node_modules